# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1215, 898)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(140, 660, 721, 181))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 300, 241, 101))
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 131, 65))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btn_model_arch = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_model_arch.setObjectName("btn_model_arch")
        self.verticalLayout_5.addWidget(self.btn_model_arch)
        self.btn_train = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_train.setObjectName("btn_train")
        self.verticalLayout_5.addWidget(self.btn_train)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(880, 40, 311, 801))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tableWidget.setFont(font)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setRowCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(1, 0, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(126)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(43)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(21)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setMinimumSectionSize(10)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 251, 281))
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.btn_plot_imgs = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_plot_imgs.setObjectName("btn_plot_imgs")
        self.verticalLayout_4.addWidget(self.btn_plot_imgs)
        self.btn_dataset_gen = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_dataset_gen.setObjectName("btn_dataset_gen")
        self.verticalLayout_4.addWidget(self.btn_dataset_gen)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 1, 0, 1, 2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.in_shape_circle = QtWidgets.QCheckBox(self.groupBox_4)
        self.in_shape_circle.setChecked(True)
        self.in_shape_circle.setObjectName("in_shape_circle")
        self.verticalLayout_3.addWidget(self.in_shape_circle)
        self.in_shape_mesh = QtWidgets.QCheckBox(self.groupBox_4)
        self.in_shape_mesh.setObjectName("in_shape_mesh")
        self.verticalLayout_3.addWidget(self.in_shape_mesh)
        self.in_shape_triangle = QtWidgets.QCheckBox(self.groupBox_4)
        self.in_shape_triangle.setObjectName("in_shape_triangle")
        self.verticalLayout_3.addWidget(self.in_shape_triangle)
        self.in_shape_plus = QtWidgets.QCheckBox(self.groupBox_4)
        self.in_shape_plus.setObjectName("in_shape_plus")
        self.verticalLayout_3.addWidget(self.in_shape_plus)
        self.in_shape_squre = QtWidgets.QCheckBox(self.groupBox_4)
        self.in_shape_squre.setObjectName("in_shape_squre")
        self.verticalLayout_3.addWidget(self.in_shape_squre)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_3)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_img_H = QtWidgets.QLabel(self.groupBox)
        self.lbl_img_H.setObjectName("lbl_img_H")
        self.horizontalLayout.addWidget(self.lbl_img_H)
        self.in_img_H = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_img_H.sizePolicy().hasHeightForWidth())
        self.in_img_H.setSizePolicy(sizePolicy)
        self.in_img_H.setObjectName("in_img_H")
        self.horizontalLayout.addWidget(self.in_img_H)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_img_H_2 = QtWidgets.QLabel(self.groupBox)
        self.lbl_img_H_2.setObjectName("lbl_img_H_2")
        self.horizontalLayout_2.addWidget(self.lbl_img_H_2)
        self.in_img_W = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_img_W.sizePolicy().hasHeightForWidth())
        self.in_img_W.setSizePolicy(sizePolicy)
        self.in_img_W.setObjectName("in_img_W")
        self.horizontalLayout_2.addWidget(self.in_img_W)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_train_dataset = QtWidgets.QLabel(self.groupBox)
        self.lbl_train_dataset.setObjectName("lbl_train_dataset")
        self.horizontalLayout_3.addWidget(self.lbl_train_dataset)
        self.in_train_dataset = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_train_dataset.sizePolicy().hasHeightForWidth())
        self.in_train_dataset.setSizePolicy(sizePolicy)
        self.in_train_dataset.setObjectName("in_train_dataset")
        self.horizontalLayout_3.addWidget(self.in_train_dataset)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_img_H_4 = QtWidgets.QLabel(self.groupBox)
        self.lbl_img_H_4.setObjectName("lbl_img_H_4")
        self.horizontalLayout_4.addWidget(self.lbl_img_H_4)
        self.in_val_dataset = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_val_dataset.sizePolicy().hasHeightForWidth())
        self.in_val_dataset.setSizePolicy(sizePolicy)
        self.in_val_dataset.setObjectName("in_val_dataset")
        self.horizontalLayout_4.addWidget(self.in_val_dataset)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_batch_size = QtWidgets.QLabel(self.groupBox)
        self.lbl_batch_size.setObjectName("lbl_batch_size")
        self.horizontalLayout_6.addWidget(self.lbl_batch_size)
        self.in_batch_size = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.in_batch_size.sizePolicy().hasHeightForWidth())
        self.in_batch_size.setSizePolicy(sizePolicy)
        self.in_batch_size.setObjectName("in_batch_size")
        self.horizontalLayout_6.addWidget(self.in_batch_size)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 1, 1, 1)
        self.btn_model_gen = QtWidgets.QPushButton(self.centralwidget)
        self.btn_model_gen.setGeometry(QtCore.QRect(20, 730, 93, 28))
        self.btn_model_gen.setObjectName("btn_model_gen")
        self.layoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 420, 166, 27))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lbl_img_H_5 = QtWidgets.QLabel(self.layoutWidget_3)
        self.lbl_img_H_5.setObjectName("lbl_img_H_5")
        self.horizontalLayout_5.addWidget(self.lbl_img_H_5)
        self.in_train_epoch_num = QtWidgets.QLineEdit(self.layoutWidget_3)
        self.in_train_epoch_num.setObjectName("in_train_epoch_num")
        self.horizontalLayout_5.addWidget(self.in_train_epoch_num)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(280, 40, 581, 361))
        self.tableWidget_2.setGridStyle(QtCore.Qt.DotLine)
        self.tableWidget_2.setRowCount(9)
        self.tableWidget_2.setColumnCount(8)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(58)
        self.tableWidget_2.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget_2.verticalHeader().setMinimumSectionSize(20)
        self.btn_train_allmodels = QtWidgets.QPushButton(self.centralwidget)
        self.btn_train_allmodels.setGeometry(QtCore.QRect(370, 470, 93, 28))
        self.btn_train_allmodels.setObjectName("btn_train_allmodels")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1215, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Configuration"))
        self.btn_model_arch.setText(_translate("MainWindow", "Design model"))
        self.btn_train.setText(_translate("MainWindow", "Train"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Model Name"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", ".."))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_3.setTitle(_translate("MainWindow", "Dataset Options"))
        self.btn_plot_imgs.setText(_translate("MainWindow", "Plot images"))
        self.btn_dataset_gen.setText(_translate("MainWindow", "Data set"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Objects"))
        self.in_shape_circle.setText(_translate("MainWindow", "Circle"))
        self.in_shape_mesh.setText(_translate("MainWindow", "Mesh"))
        self.in_shape_triangle.setText(_translate("MainWindow", "Triangle"))
        self.in_shape_plus.setText(_translate("MainWindow", "Plus"))
        self.in_shape_squre.setText(_translate("MainWindow", "Squre"))
        self.groupBox.setTitle(_translate("MainWindow", "Size and numbers"))
        self.lbl_img_H.setText(_translate("MainWindow", "Height "))
        self.in_img_H.setText(_translate("MainWindow", "192"))
        self.lbl_img_H_2.setText(_translate("MainWindow", "Weight"))
        self.in_img_W.setText(_translate("MainWindow", "192"))
        self.lbl_train_dataset.setText(_translate("MainWindow", "Train"))
        self.in_train_dataset.setText(_translate("MainWindow", "200"))
        self.lbl_img_H_4.setText(_translate("MainWindow", "Val   "))
        self.in_val_dataset.setText(_translate("MainWindow", "20"))
        self.lbl_batch_size.setText(_translate("MainWindow", "Batch"))
        self.in_batch_size.setText(_translate("MainWindow", "50"))
        self.btn_model_gen.setText(_translate("MainWindow", "Model"))
        self.lbl_img_H_5.setText(_translate("MainWindow", "Epoch_number"))
        self.in_train_epoch_num.setText(_translate("MainWindow", "20"))
        self.btn_train_allmodels.setText(_translate("MainWindow", "Train All"))
