# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1001, 754)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(490, 30, 491, 651))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 111, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.widget = QtWidgets.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(20, 20, 81, 61))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_img_H = QtWidgets.QLabel(self.widget)
        self.lbl_img_H.setObjectName("lbl_img_H")
        self.horizontalLayout.addWidget(self.lbl_img_H)
        self.in_img_H = QtWidgets.QLineEdit(self.widget)
        self.in_img_H.setObjectName("in_img_H")
        self.horizontalLayout.addWidget(self.in_img_H)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_img_H_2 = QtWidgets.QLabel(self.widget)
        self.lbl_img_H_2.setObjectName("lbl_img_H_2")
        self.horizontalLayout_2.addWidget(self.lbl_img_H_2)
        self.in_img_W = QtWidgets.QLineEdit(self.widget)
        self.in_img_W.setObjectName("in_img_W")
        self.horizontalLayout_2.addWidget(self.in_img_W)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_2)
        self.groupBox.setGeometry(QtCore.QRect(0, 90, 101, 101))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(20, 20, 71, 61))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_train_dataset = QtWidgets.QLabel(self.layoutWidget_2)
        self.lbl_train_dataset.setObjectName("lbl_train_dataset")
        self.horizontalLayout_3.addWidget(self.lbl_train_dataset)
        self.in_train_dataset = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.in_train_dataset.setObjectName("in_train_dataset")
        self.horizontalLayout_3.addWidget(self.in_train_dataset)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lbl_img_H_4 = QtWidgets.QLabel(self.layoutWidget_2)
        self.lbl_img_H_4.setObjectName("lbl_img_H_4")
        self.horizontalLayout_4.addWidget(self.lbl_img_H_4)
        self.in_val_dataset = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.in_val_dataset.setObjectName("in_val_dataset")
        self.horizontalLayout_4.addWidget(self.in_val_dataset)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.btn_dataset_gen = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_dataset_gen.setGeometry(QtCore.QRect(10, 190, 93, 28))
        self.btn_dataset_gen.setObjectName("btn_dataset_gen")
        self.btn_train = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_train.setGeometry(QtCore.QRect(10, 250, 93, 28))
        self.btn_train.setObjectName("btn_train")
        self.btn_model_gen = QtWidgets.QPushButton(self.groupBox_2)
        self.btn_model_gen.setGeometry(QtCore.QRect(10, 220, 93, 28))
        self.btn_model_gen.setObjectName("btn_model_gen")
        self.btn_model_arch = QtWidgets.QPushButton(self.centralwidget)
        self.btn_model_arch.setGeometry(QtCore.QRect(30, 340, 93, 28))
        self.btn_model_arch.setObjectName("btn_model_arch")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1001, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Configuration"))
        self.lbl_img_H.setText(_translate("MainWindow", "Height "))
        self.in_img_H.setText(_translate("MainWindow", "192"))
        self.lbl_img_H_2.setText(_translate("MainWindow", "Weight"))
        self.in_img_W.setText(_translate("MainWindow", "192"))
        self.groupBox.setTitle(_translate("MainWindow", "Data Set"))
        self.lbl_train_dataset.setText(_translate("MainWindow", "Train"))
        self.in_train_dataset.setText(_translate("MainWindow", "200"))
        self.lbl_img_H_4.setText(_translate("MainWindow", "Val   "))
        self.in_val_dataset.setText(_translate("MainWindow", "20"))
        self.btn_dataset_gen.setText(_translate("MainWindow", "Data set"))
        self.btn_train.setText(_translate("MainWindow", "Train"))
        self.btn_model_gen.setText(_translate("MainWindow", "Model"))
        self.btn_model_arch.setText(_translate("MainWindow", "Design model"))

