dataset:
    path: data
phase: test

category: person, car , bicycle , bus , motorbike , train , aeroplane , chair , bottle , dining table , potted ,  plant , tv monitor , sofa , bird , cat , cow , dog , horse , sheep
mysql:
    host: localhost
    user: root
    passwd: my secret password
    db: write-math
other:
    preprocessing_queue:
        - preprocessing.scale_and_center
        - preprocessing.dot_reduction
        - preprocessing.connect_lines
    use_anonymous: yes